pipeline {
    agent {
        kubernetes {
            defaultContainer 'kubectl'
            yaml '''
apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins

  containers:
  - name: jnlp
    image: jenkins/inbound-agent:latest-jdk21
    args: ['$(JENKINS_SECRET)', '$(JENKINS_NAME)']

  - name: kubectl
    image: registry.k8s.io/kubectl:v1.30.14
    command:
      - cat
    tty: true
'''
        }
    }

    stages {

        stage('Checkout Repository') {
            steps {
                checkout scm
            }
        }

        stage('Deploy Application') {
            steps {
                container('kubectl') {
                    withVault(
                        configuration: [
                            vaultUrl: 'http://vault.vault:8200',
                            vaultCredentialId: 'vault-k8s',
                            engineVersion: 2
                        ],
                        vaultSecrets: [[
                            path: 'secret/bank_app',
                            secretValues: [
                                [vaultKey: 'token',  envVar: 'KUBE_TOKEN'],
                                [vaultKey: 'server', envVar: 'KUBE_SERVER'],
                                [vaultKey: 'ca.crt', envVar: 'KUBE_CA']
                            ]
                        ]]
                    ) {

                        sh '''
                            set -e

                            echo "$KUBE_CA" > ca.crt

                            echo "Checking kubectl..."
                            kubectl version --client

                            echo "Applying manifests..."

                            kubectl \
                              --server="$KUBE_SERVER" \
                              --token="$KUBE_TOKEN" \
                              --certificate-authority=ca.crt \
                              apply -f bank_app/

                            echo "Waiting for rollout..."

                            kubectl \
                              --server="$KUBE_SERVER" \
                              --token="$KUBE_TOKEN" \
                              --certificate-authority=ca.crt \
                              rollout status deployment/bankapp \
                              -n bankapp \
                              --timeout=300s
                        '''
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }

        success {
            echo "Application deployed successfully."
        }

        failure {
            echo "Application deployment failed."
        }
    }
}
