pipeline {
    agent {
        kubernetes {
            yaml '''
apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins
  containers:
  - name: kubectl
    image: bitnami/kubectl:latest
    command:
    - sleep
    args:
    - infinity
'''
            defaultContainer 'kubectl'
        }
    }

    stages {

        stage('Checkout Repository') {
            steps {
                checkout scm
            }
        }

        stage('Deploy Application') {
            steps {
                withVault(
                    configuration: [
                        vaultUrl: 'http://vault.vault:8200',
                        vaultCredentialId: 'vault-k8s',
                        engineVersion: 2
                    ],
                    vaultSecrets: [[
                        path: 'secret/bank_app',
                        secretValues: [
                            [vaultKey: 'token',  envVar: 'KUBE_TOKEN'],
                            [vaultKey: 'server', envVar: 'KUBE_SERVER'],
                            [vaultKey: 'ca.crt', envVar: 'KUBE_CA']
                        ]
                    ]]
                ) {

                    sh '''
                        echo "$KUBE_CA" > ca.crt

                        kubectl \
                          --server="$KUBE_SERVER" \
                          --token="$KUBE_TOKEN" \
                          --certificate-authority=ca.crt \
                          apply -f bank_app/

                        kubectl \
                          --server="$KUBE_SERVER" \
                          --token="$KUBE_TOKEN" \
                          --certificate-authority=ca.crt \
                          rollout status deployment/bankapp \
                          -n bankapp \
                          --timeout=300s
                    '''
                }
            }
        }
    }
}
